/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    CanvasEditor: typeof import('./src/components/editor/CanvasEditor.vue')['default']
    ContextMenu: typeof import('./src/components/editor/ContextMenu.vue')['default']
    LayerPanel: typeof import('./src/components/editor/LayerPanel.vue')['default']
    PropertyPanel: typeof import('./src/components/editor/PropertyPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./src/components/editor/Toolbar.vue')['default']
  }
}

// For TSX support
declare global {
  const Button: typeof import('./src/components/ui/button/Button.vue')['default']
  const CanvasEditor: typeof import('./src/components/editor/CanvasEditor.vue')['default']
  const ContextMenu: typeof import('./src/components/editor/ContextMenu.vue')['default']
  const LayerPanel: typeof import('./src/components/editor/LayerPanel.vue')['default']
  const PropertyPanel: typeof import('./src/components/editor/PropertyPanel.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Toolbar: typeof import('./src/components/editor/Toolbar.vue')['default']
}