/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertNode: typeof import('./src/components/v2/nodes/AlertNode.vue')['default']
    CanvasEditorV2: typeof import('./src/components/v2/editor/CanvasEditorV2.vue')['default']
    CanvasPropertiesV2: typeof import('./src/components/v2/editor/properties/CanvasPropertiesV2.vue')['default']
    ChartNode: typeof import('./src/components/v2/nodes/ChartNode.vue')['default']
    CoolingFan: typeof import('./src/components/v2/nodes/CoolingFan.vue')['default']
    CountDownNode: typeof import('./src/components/v2/nodes/CountDownNode.vue')['default']
    DigitalNode: typeof import('./src/components/v2/nodes/DigitalNode.vue')['default']
    EdgePropertiesV2: typeof import('./src/components/v2/editor/properties/EdgePropertiesV2.vue')['default']
    FlowNode: typeof import('./src/components/v2/nodes/FlowNode.vue')['default']
    GaugeNode: typeof import('./src/components/v2/nodes/GaugeNode.vue')['default']
    HeaderV2: typeof import('./src/components/v2/editor/HeaderV2.vue')['default']
    IconNode: typeof import('./src/components/v2/nodes/IconNode.vue')['default']
    IconPickerDialog: typeof import('./src/components/v2/editor/IconPickerDialog.vue')['default']
    LayerPanelV2: typeof import('./src/components/v2/editor/LayerPanelV2.vue')['default']
    ListNode: typeof import('./src/components/v2/nodes/ListNode.vue')['default']
    NodePropertiesV2: typeof import('./src/components/v2/editor/properties/NodePropertiesV2.vue')['default']
    PortConfigPanel: typeof import('./src/components/v2/editor/properties/PortConfigPanel.vue')['default']
    ProgressBarNode: typeof import('./src/components/v2/nodes/ProgressBarNode.vue')['default']
    PropertyPanelV2: typeof import('./src/components/v2/editor/PropertyPanelV2.vue')['default']
    ReferLineV2: typeof import('./src/components/v2/editor/ReferLineV2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RulerV2: typeof import('./src/components/v2/editor/RulerV2.vue')['default']
    SketchRulerV2: typeof import('./src/components/v2/editor/SketchRulerV2.vue')['default']
    StorageTank: typeof import('./src/components/v2/nodes/StorageTank.vue')['default']
    TableNode: typeof import('./src/components/v2/nodes/TableNode.vue')['default']
    TimelineNode: typeof import('./src/components/v2/nodes/TimelineNode.vue')['default']
    ToolbarV2: typeof import('./src/components/v2/editor/ToolbarV2.vue')['default']
  }
}

// For TSX support
declare global {
  const AlertNode: typeof import('./src/components/v2/nodes/AlertNode.vue')['default']
  const CanvasEditorV2: typeof import('./src/components/v2/editor/CanvasEditorV2.vue')['default']
  const CanvasPropertiesV2: typeof import('./src/components/v2/editor/properties/CanvasPropertiesV2.vue')['default']
  const ChartNode: typeof import('./src/components/v2/nodes/ChartNode.vue')['default']
  const CoolingFan: typeof import('./src/components/v2/nodes/CoolingFan.vue')['default']
  const CountDownNode: typeof import('./src/components/v2/nodes/CountDownNode.vue')['default']
  const DigitalNode: typeof import('./src/components/v2/nodes/DigitalNode.vue')['default']
  const EdgePropertiesV2: typeof import('./src/components/v2/editor/properties/EdgePropertiesV2.vue')['default']
  const FlowNode: typeof import('./src/components/v2/nodes/FlowNode.vue')['default']
  const GaugeNode: typeof import('./src/components/v2/nodes/GaugeNode.vue')['default']
  const HeaderV2: typeof import('./src/components/v2/editor/HeaderV2.vue')['default']
  const IconNode: typeof import('./src/components/v2/nodes/IconNode.vue')['default']
  const IconPickerDialog: typeof import('./src/components/v2/editor/IconPickerDialog.vue')['default']
  const LayerPanelV2: typeof import('./src/components/v2/editor/LayerPanelV2.vue')['default']
  const ListNode: typeof import('./src/components/v2/nodes/ListNode.vue')['default']
  const NodePropertiesV2: typeof import('./src/components/v2/editor/properties/NodePropertiesV2.vue')['default']
  const PortConfigPanel: typeof import('./src/components/v2/editor/properties/PortConfigPanel.vue')['default']
  const ProgressBarNode: typeof import('./src/components/v2/nodes/ProgressBarNode.vue')['default']
  const PropertyPanelV2: typeof import('./src/components/v2/editor/PropertyPanelV2.vue')['default']
  const ReferLineV2: typeof import('./src/components/v2/editor/ReferLineV2.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const RulerV2: typeof import('./src/components/v2/editor/RulerV2.vue')['default']
  const SketchRulerV2: typeof import('./src/components/v2/editor/SketchRulerV2.vue')['default']
  const StorageTank: typeof import('./src/components/v2/nodes/StorageTank.vue')['default']
  const TableNode: typeof import('./src/components/v2/nodes/TableNode.vue')['default']
  const TimelineNode: typeof import('./src/components/v2/nodes/TimelineNode.vue')['default']
  const ToolbarV2: typeof import('./src/components/v2/editor/ToolbarV2.vue')['default']
}