/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanvasEditorV2: typeof import('./src/components/v2/editor/CanvasEditorV2.vue')['default']
    CanvasPropertiesV2: typeof import('./src/components/v2/editor/properties/CanvasPropertiesV2.vue')['default']
    EdgePropertiesV2: typeof import('./src/components/v2/editor/properties/EdgePropertiesV2.vue')['default']
    FlowNode: typeof import('./src/components/v2/nodes/FlowNode.vue')['default']
    HeaderV2: typeof import('./src/components/v2/editor/HeaderV2.vue')['default']
    IconPickerDialog: typeof import('./src/components/v2/editor/IconPickerDialog.vue')['default']
    LayerPanelV2: typeof import('./src/components/v2/editor/LayerPanelV2.vue')['default']
    NodePropertiesV2: typeof import('./src/components/v2/editor/properties/NodePropertiesV2.vue')['default']
    PortConfigPanel: typeof import('./src/components/v2/editor/properties/PortConfigPanel.vue')['default']
    PropertyPanelV2: typeof import('./src/components/v2/editor/PropertyPanelV2.vue')['default']
    ReferLineV2: typeof import('./src/components/v2/editor/ReferLineV2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RulerV2: typeof import('./src/components/v2/editor/RulerV2.vue')['default']
    SketchRulerV2: typeof import('./src/components/v2/editor/SketchRulerV2.vue')['default']
    ToolbarV2: typeof import('./src/components/v2/editor/ToolbarV2.vue')['default']
  }
}

// For TSX support
declare global {
  const CanvasEditorV2: typeof import('./src/components/v2/editor/CanvasEditorV2.vue')['default']
  const CanvasPropertiesV2: typeof import('./src/components/v2/editor/properties/CanvasPropertiesV2.vue')['default']
  const EdgePropertiesV2: typeof import('./src/components/v2/editor/properties/EdgePropertiesV2.vue')['default']
  const FlowNode: typeof import('./src/components/v2/nodes/FlowNode.vue')['default']
  const HeaderV2: typeof import('./src/components/v2/editor/HeaderV2.vue')['default']
  const IconPickerDialog: typeof import('./src/components/v2/editor/IconPickerDialog.vue')['default']
  const LayerPanelV2: typeof import('./src/components/v2/editor/LayerPanelV2.vue')['default']
  const NodePropertiesV2: typeof import('./src/components/v2/editor/properties/NodePropertiesV2.vue')['default']
  const PortConfigPanel: typeof import('./src/components/v2/editor/properties/PortConfigPanel.vue')['default']
  const PropertyPanelV2: typeof import('./src/components/v2/editor/PropertyPanelV2.vue')['default']
  const ReferLineV2: typeof import('./src/components/v2/editor/ReferLineV2.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const RulerV2: typeof import('./src/components/v2/editor/RulerV2.vue')['default']
  const SketchRulerV2: typeof import('./src/components/v2/editor/SketchRulerV2.vue')['default']
  const ToolbarV2: typeof import('./src/components/v2/editor/ToolbarV2.vue')['default']
}